//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace ManWo_Accounting {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("PhieuNhapDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class PhieuNhapDataSet : global::System.Data.DataSet {
        
        private tPhieuNhapHangHoaDataTable tabletPhieuNhapHangHoa;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public PhieuNhapDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected PhieuNhapDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["tPhieuNhapHangHoa"] != null)) {
                    base.Tables.Add(new tPhieuNhapHangHoaDataTable(ds.Tables["tPhieuNhapHangHoa"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tPhieuNhapHangHoaDataTable tPhieuNhapHangHoa {
            get {
                return this.tabletPhieuNhapHangHoa;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            PhieuNhapDataSet cln = ((PhieuNhapDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["tPhieuNhapHangHoa"] != null)) {
                    base.Tables.Add(new tPhieuNhapHangHoaDataTable(ds.Tables["tPhieuNhapHangHoa"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabletPhieuNhapHangHoa = ((tPhieuNhapHangHoaDataTable)(base.Tables["tPhieuNhapHangHoa"]));
            if ((initTable == true)) {
                if ((this.tabletPhieuNhapHangHoa != null)) {
                    this.tabletPhieuNhapHangHoa.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void InitClass() {
            this.DataSetName = "PhieuNhapDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/PhieuNhapDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabletPhieuNhapHangHoa = new tPhieuNhapHangHoaDataTable();
            base.Tables.Add(this.tabletPhieuNhapHangHoa);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private bool ShouldSerializetPhieuNhapHangHoa() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            PhieuNhapDataSet ds = new PhieuNhapDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public delegate void tPhieuNhapHangHoaRowChangeEventHandler(object sender, tPhieuNhapHangHoaRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class tPhieuNhapHangHoaDataTable : global::System.Data.TypedTableBase<tPhieuNhapHangHoaRow> {
            
            private global::System.Data.DataColumn columncMaChungTu;
            
            private global::System.Data.DataColumn columncLoaiChungTu;
            
            private global::System.Data.DataColumn columndNgayChungTu;
            
            private global::System.Data.DataColumn columncSoChungTu;
            
            private global::System.Data.DataColumn columncMaNguoiBan;
            
            private global::System.Data.DataColumn columncTenNguoiBan;
            
            private global::System.Data.DataColumn columncMaSoThueNguoiBan;
            
            private global::System.Data.DataColumn columncTaiKhoanNo;
            
            private global::System.Data.DataColumn columncTaiKhoanNoGTGT;
            
            private global::System.Data.DataColumn columncTaiKhoanCo;
            
            private global::System.Data.DataColumn columnDataColumn1;
            
            private global::System.Data.DataColumn columncSoSeRi;
            
            private global::System.Data.DataColumn columncSoHoaDon;
            
            private global::System.Data.DataColumn columndNgayHoaDon;
            
            private global::System.Data.DataColumn columnnThueSuat;
            
            private global::System.Data.DataColumn columnnThueGTGT;
            
            private global::System.Data.DataColumn columncMatHang;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public tPhieuNhapHangHoaDataTable() {
                this.TableName = "tPhieuNhapHangHoa";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal tPhieuNhapHangHoaDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected tPhieuNhapHangHoaDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cMaChungTuColumn {
                get {
                    return this.columncMaChungTu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cLoaiChungTuColumn {
                get {
                    return this.columncLoaiChungTu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn dNgayChungTuColumn {
                get {
                    return this.columndNgayChungTu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cSoChungTuColumn {
                get {
                    return this.columncSoChungTu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cMaNguoiBanColumn {
                get {
                    return this.columncMaNguoiBan;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cTenNguoiBanColumn {
                get {
                    return this.columncTenNguoiBan;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cMaSoThueNguoiBanColumn {
                get {
                    return this.columncMaSoThueNguoiBan;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cTaiKhoanNoColumn {
                get {
                    return this.columncTaiKhoanNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cTaiKhoanNoGTGTColumn {
                get {
                    return this.columncTaiKhoanNoGTGT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cTaiKhoanCoColumn {
                get {
                    return this.columncTaiKhoanCo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn DataColumn1Column {
                get {
                    return this.columnDataColumn1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cSoSeRiColumn {
                get {
                    return this.columncSoSeRi;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cSoHoaDonColumn {
                get {
                    return this.columncSoHoaDon;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn dNgayHoaDonColumn {
                get {
                    return this.columndNgayHoaDon;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn nThueSuatColumn {
                get {
                    return this.columnnThueSuat;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn nThueGTGTColumn {
                get {
                    return this.columnnThueGTGT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cMatHangColumn {
                get {
                    return this.columncMatHang;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public tPhieuNhapHangHoaRow this[int index] {
                get {
                    return ((tPhieuNhapHangHoaRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event tPhieuNhapHangHoaRowChangeEventHandler tPhieuNhapHangHoaRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event tPhieuNhapHangHoaRowChangeEventHandler tPhieuNhapHangHoaRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event tPhieuNhapHangHoaRowChangeEventHandler tPhieuNhapHangHoaRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event tPhieuNhapHangHoaRowChangeEventHandler tPhieuNhapHangHoaRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void AddtPhieuNhapHangHoaRow(tPhieuNhapHangHoaRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public tPhieuNhapHangHoaRow AddtPhieuNhapHangHoaRow(
                        string cMaChungTu, 
                        string cLoaiChungTu, 
                        string dNgayChungTu, 
                        string cSoChungTu, 
                        string cMaNguoiBan, 
                        string cTenNguoiBan, 
                        string cMaSoThueNguoiBan, 
                        string cTaiKhoanNo, 
                        string cTaiKhoanNoGTGT, 
                        string cTaiKhoanCo, 
                        string DataColumn1, 
                        string cSoSeRi, 
                        string cSoHoaDon, 
                        string dNgayHoaDon, 
                        string nThueSuat, 
                        string nThueGTGT, 
                        string cMatHang) {
                tPhieuNhapHangHoaRow rowtPhieuNhapHangHoaRow = ((tPhieuNhapHangHoaRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        cMaChungTu,
                        cLoaiChungTu,
                        dNgayChungTu,
                        cSoChungTu,
                        cMaNguoiBan,
                        cTenNguoiBan,
                        cMaSoThueNguoiBan,
                        cTaiKhoanNo,
                        cTaiKhoanNoGTGT,
                        cTaiKhoanCo,
                        DataColumn1,
                        cSoSeRi,
                        cSoHoaDon,
                        dNgayHoaDon,
                        nThueSuat,
                        nThueGTGT,
                        cMatHang};
                rowtPhieuNhapHangHoaRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowtPhieuNhapHangHoaRow);
                return rowtPhieuNhapHangHoaRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                tPhieuNhapHangHoaDataTable cln = ((tPhieuNhapHangHoaDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new tPhieuNhapHangHoaDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal void InitVars() {
                this.columncMaChungTu = base.Columns["cMaChungTu"];
                this.columncLoaiChungTu = base.Columns["cLoaiChungTu"];
                this.columndNgayChungTu = base.Columns["dNgayChungTu"];
                this.columncSoChungTu = base.Columns["cSoChungTu"];
                this.columncMaNguoiBan = base.Columns["cMaNguoiBan"];
                this.columncTenNguoiBan = base.Columns["cTenNguoiBan"];
                this.columncMaSoThueNguoiBan = base.Columns["cMaSoThueNguoiBan"];
                this.columncTaiKhoanNo = base.Columns["cTaiKhoanNo"];
                this.columncTaiKhoanNoGTGT = base.Columns["cTaiKhoanNoGTGT"];
                this.columncTaiKhoanCo = base.Columns["cTaiKhoanCo"];
                this.columnDataColumn1 = base.Columns["DataColumn1"];
                this.columncSoSeRi = base.Columns["cSoSeRi"];
                this.columncSoHoaDon = base.Columns["cSoHoaDon"];
                this.columndNgayHoaDon = base.Columns["dNgayHoaDon"];
                this.columnnThueSuat = base.Columns["nThueSuat"];
                this.columnnThueGTGT = base.Columns["nThueGTGT"];
                this.columncMatHang = base.Columns["cMatHang"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            private void InitClass() {
                this.columncMaChungTu = new global::System.Data.DataColumn("cMaChungTu", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncMaChungTu);
                this.columncLoaiChungTu = new global::System.Data.DataColumn("cLoaiChungTu", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncLoaiChungTu);
                this.columndNgayChungTu = new global::System.Data.DataColumn("dNgayChungTu", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndNgayChungTu);
                this.columncSoChungTu = new global::System.Data.DataColumn("cSoChungTu", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncSoChungTu);
                this.columncMaNguoiBan = new global::System.Data.DataColumn("cMaNguoiBan", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncMaNguoiBan);
                this.columncTenNguoiBan = new global::System.Data.DataColumn("cTenNguoiBan", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncTenNguoiBan);
                this.columncMaSoThueNguoiBan = new global::System.Data.DataColumn("cMaSoThueNguoiBan", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncMaSoThueNguoiBan);
                this.columncTaiKhoanNo = new global::System.Data.DataColumn("cTaiKhoanNo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncTaiKhoanNo);
                this.columncTaiKhoanNoGTGT = new global::System.Data.DataColumn("cTaiKhoanNoGTGT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncTaiKhoanNoGTGT);
                this.columncTaiKhoanCo = new global::System.Data.DataColumn("cTaiKhoanCo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncTaiKhoanCo);
                this.columnDataColumn1 = new global::System.Data.DataColumn("DataColumn1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataColumn1);
                this.columncSoSeRi = new global::System.Data.DataColumn("cSoSeRi", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncSoSeRi);
                this.columncSoHoaDon = new global::System.Data.DataColumn("cSoHoaDon", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncSoHoaDon);
                this.columndNgayHoaDon = new global::System.Data.DataColumn("dNgayHoaDon", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndNgayHoaDon);
                this.columnnThueSuat = new global::System.Data.DataColumn("nThueSuat", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnThueSuat);
                this.columnnThueGTGT = new global::System.Data.DataColumn("nThueGTGT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnThueGTGT);
                this.columncMatHang = new global::System.Data.DataColumn("cMatHang", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncMatHang);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public tPhieuNhapHangHoaRow NewtPhieuNhapHangHoaRow() {
                return ((tPhieuNhapHangHoaRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new tPhieuNhapHangHoaRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(tPhieuNhapHangHoaRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tPhieuNhapHangHoaRowChanged != null)) {
                    this.tPhieuNhapHangHoaRowChanged(this, new tPhieuNhapHangHoaRowChangeEvent(((tPhieuNhapHangHoaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tPhieuNhapHangHoaRowChanging != null)) {
                    this.tPhieuNhapHangHoaRowChanging(this, new tPhieuNhapHangHoaRowChangeEvent(((tPhieuNhapHangHoaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tPhieuNhapHangHoaRowDeleted != null)) {
                    this.tPhieuNhapHangHoaRowDeleted(this, new tPhieuNhapHangHoaRowChangeEvent(((tPhieuNhapHangHoaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tPhieuNhapHangHoaRowDeleting != null)) {
                    this.tPhieuNhapHangHoaRowDeleting(this, new tPhieuNhapHangHoaRowChangeEvent(((tPhieuNhapHangHoaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void RemovetPhieuNhapHangHoaRow(tPhieuNhapHangHoaRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                PhieuNhapDataSet ds = new PhieuNhapDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "tPhieuNhapHangHoaDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class tPhieuNhapHangHoaRow : global::System.Data.DataRow {
            
            private tPhieuNhapHangHoaDataTable tabletPhieuNhapHangHoa;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal tPhieuNhapHangHoaRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabletPhieuNhapHangHoa = ((tPhieuNhapHangHoaDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cMaChungTu {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.cMaChungTuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cMaChungTu\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.cMaChungTuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cLoaiChungTu {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.cLoaiChungTuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cLoaiChungTu\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.cLoaiChungTuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string dNgayChungTu {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.dNgayChungTuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'dNgayChungTu\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.dNgayChungTuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cSoChungTu {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.cSoChungTuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cSoChungTu\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.cSoChungTuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cMaNguoiBan {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.cMaNguoiBanColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cMaNguoiBan\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.cMaNguoiBanColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cTenNguoiBan {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.cTenNguoiBanColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cTenNguoiBan\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.cTenNguoiBanColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cMaSoThueNguoiBan {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.cMaSoThueNguoiBanColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cMaSoThueNguoiBan\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.cMaSoThueNguoiBanColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cTaiKhoanNo {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.cTaiKhoanNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cTaiKhoanNo\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.cTaiKhoanNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cTaiKhoanNoGTGT {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.cTaiKhoanNoGTGTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cTaiKhoanNoGTGT\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.cTaiKhoanNoGTGTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cTaiKhoanCo {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.cTaiKhoanCoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cTaiKhoanCo\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.cTaiKhoanCoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string DataColumn1 {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.DataColumn1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DataColumn1\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.DataColumn1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cSoSeRi {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.cSoSeRiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cSoSeRi\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.cSoSeRiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cSoHoaDon {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.cSoHoaDonColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cSoHoaDon\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.cSoHoaDonColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string dNgayHoaDon {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.dNgayHoaDonColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'dNgayHoaDon\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.dNgayHoaDonColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string nThueSuat {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.nThueSuatColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nThueSuat\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.nThueSuatColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string nThueGTGT {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.nThueGTGTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nThueGTGT\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.nThueGTGTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cMatHang {
                get {
                    try {
                        return ((string)(this[this.tabletPhieuNhapHangHoa.cMatHangColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cMatHang\' in table \'tPhieuNhapHangHoa\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletPhieuNhapHangHoa.cMatHangColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscMaChungTuNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.cMaChungTuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcMaChungTuNull() {
                this[this.tabletPhieuNhapHangHoa.cMaChungTuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscLoaiChungTuNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.cLoaiChungTuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcLoaiChungTuNull() {
                this[this.tabletPhieuNhapHangHoa.cLoaiChungTuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsdNgayChungTuNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.dNgayChungTuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetdNgayChungTuNull() {
                this[this.tabletPhieuNhapHangHoa.dNgayChungTuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscSoChungTuNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.cSoChungTuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcSoChungTuNull() {
                this[this.tabletPhieuNhapHangHoa.cSoChungTuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscMaNguoiBanNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.cMaNguoiBanColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcMaNguoiBanNull() {
                this[this.tabletPhieuNhapHangHoa.cMaNguoiBanColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscTenNguoiBanNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.cTenNguoiBanColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcTenNguoiBanNull() {
                this[this.tabletPhieuNhapHangHoa.cTenNguoiBanColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscMaSoThueNguoiBanNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.cMaSoThueNguoiBanColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcMaSoThueNguoiBanNull() {
                this[this.tabletPhieuNhapHangHoa.cMaSoThueNguoiBanColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscTaiKhoanNoNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.cTaiKhoanNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcTaiKhoanNoNull() {
                this[this.tabletPhieuNhapHangHoa.cTaiKhoanNoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscTaiKhoanNoGTGTNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.cTaiKhoanNoGTGTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcTaiKhoanNoGTGTNull() {
                this[this.tabletPhieuNhapHangHoa.cTaiKhoanNoGTGTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscTaiKhoanCoNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.cTaiKhoanCoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcTaiKhoanCoNull() {
                this[this.tabletPhieuNhapHangHoa.cTaiKhoanCoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsDataColumn1Null() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.DataColumn1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetDataColumn1Null() {
                this[this.tabletPhieuNhapHangHoa.DataColumn1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscSoSeRiNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.cSoSeRiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcSoSeRiNull() {
                this[this.tabletPhieuNhapHangHoa.cSoSeRiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscSoHoaDonNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.cSoHoaDonColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcSoHoaDonNull() {
                this[this.tabletPhieuNhapHangHoa.cSoHoaDonColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsdNgayHoaDonNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.dNgayHoaDonColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetdNgayHoaDonNull() {
                this[this.tabletPhieuNhapHangHoa.dNgayHoaDonColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsnThueSuatNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.nThueSuatColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetnThueSuatNull() {
                this[this.tabletPhieuNhapHangHoa.nThueSuatColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsnThueGTGTNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.nThueGTGTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetnThueGTGTNull() {
                this[this.tabletPhieuNhapHangHoa.nThueGTGTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscMatHangNull() {
                return this.IsNull(this.tabletPhieuNhapHangHoa.cMatHangColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcMatHangNull() {
                this[this.tabletPhieuNhapHangHoa.cMatHangColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public class tPhieuNhapHangHoaRowChangeEvent : global::System.EventArgs {
            
            private tPhieuNhapHangHoaRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public tPhieuNhapHangHoaRowChangeEvent(tPhieuNhapHangHoaRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public tPhieuNhapHangHoaRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591